pipeline:
  restore-cache:
    image: drillster/drone-volume-cache
    restore: true
    mount:
      - ./node_modules
      - ./vendor
    volumes:
      - /tmp/drone-cache:/cache

  install_php_dependencies:
    image: composer:1.4.2
    commands:
      - composer install

  install_node_dependencies:
    image: node:6
    commands:
      - npm install
      - npm run production

  rebuild-cache:
    image: drillster/drone-volume-cache
    rebuild: true
    mount:
      - ./node_modules
      - ./vendor
    volumes:
      - /tmp/drone-cache:/cache

  prepare_tests:
    image: francken/php
    commands:
      - cp .env.example .env
      - php artisan key:generate
      - php artisan migrate:refresh --seed

  run_tests:
    image: francken/php-with-xdebug
    commands:
      - vendor/bin/phpunit

  send_test_coverage_to_coveralls:
    image: francken/php-with-xdebug
    secrets: [COVERALLS_REPO_TOKEN]
    environment:
      - COVERALLS_REPO_TOKEN=${COVERALLS_REPO_TOKEN}
      - COVERALLS_RUN_LOCALLY=1
    commands:
      - vendor/bin/coveralls

  notify-and-speak-over-ssh:
    image: appleboy/drone-ssh
    host: 129.125.7.9
    username: scriptcie
    secrets: [SSH_PASSWORD]
    password: ${SSH_PASSWORD}
    port: 22
    script:
      - /home/scriptcie/drone/notifications/it-broke.sh
    when:
      status: failure
