language: php

php:
    - 7.0

env:
  global:
    - setup=basic
    - APP_ENV=testing
    - APP_DEBUG=true
    - APP_KEY=SomeRandomStringSomeRandomString

before_install:
  - composer self-update

install:
  - travis_retry composer install --no-interaction --prefer-source
