language: php

php:
    - 7.0

env:
  global:
    - setup=basic
    - APP_ENV=testing
    - APP_DEBUG=true
    - APP_KEY=SomeRandomStringSomeRandomString

before_script:
  - pecl install imagick
  - composer selfupdate
  - composer install --prefer-dist

after_script:
  - vendor/bin/coveralls
