language: php

php:
  - 7.0

env:
  global:
    - setup=basic
    - APP_ENV=testing
    - APP_DEBUG=true
    - APP_KEY=SomeRandomStringSomeRandomString

before_install:
  - sudo add-apt-repository -y ppa:moti-p/cc
  - sudo apt-get update
  - sudo apt-get -y --reinstall install imagemagick
  - yes | pecl install imagick-beta

before_script:
  - composer selfupdate
  - travis_retry composer install --prefer-source --no-interaction

after_script:
  - vendor/bin/coveralls

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.php-cs-fixer
