sudo: required

language: php

php:
  - 7.3

env:
  global:
    - setup=basic
    - APP_ENV=testing
    - APP_DEBUG=true
    - APP_KEY=SomeRandomStringSomeRandomString

before_script:
  - composer selfupdate
  - travis_retry composer install --prefer-source --no-interaction

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.php-cs-fixer
