version: '2'

networks:
  traefik:
    external:
      name: traefik_webgateway

services:
  php-base:
    build:
      dockerfile: Dockerfile-base
      context: ./docker/php
    image: francken/php-base

  composer:
    image: composer:1.7
    volumes_from:
      - php
    working_dir: /var/www/francken

  npm:
    image: node:14.5
    volumes_from:
      - php
    working_dir: /var/www/francken

  php:
    image: francken/php
    links:
      - mysql
      - legacy-db
      - redis
      - mailhog
    working_dir: /var/www/francken
    volumes:
      - ./:/var/www/francken
    environment:
      - CACHE_DRIVER=redis
      - SESSION_DRIVER=redis
      - QUEUE_DRIVER=redis
      - QUEUE_CONNECTION=redis
      - REDIS_HOST=redis
      - APP_URL=http://francken.nl.localhost
      - MAIL_HOST=mailhog
      - MAIL_PORT=1025

  scheduler:
    image: francken/scheduler
    links:
      - legacy-db
      - redis
    working_dir: /var/www/francken
    volumes:
      - ./:/var/www/francken
    restart: always

  queue-worker:
    image: francken/scheduler
    links:
      - legacy-db
      - redis
      - mailhog
    working_dir: /var/www/francken
    volumes:
      - ./:/var/www/francken
    restart: always
    command: php artisan horizon
    environment:
      - CACHE_DRIVER=redis
      - SESSION_DRIVER=redis
      - QUEUE_DRIVER=redis
      - QUEUE_CONNECTION=redis
      - REDIS_HOST=redis
      - APP_URL=http://francken.nl.localhost
      - MAIL_HOST=mailhog
      - MAIL_PORT=1025

  nginx:
    build:
      dockerfile: Dockerfile
      context: ./docker/nginx
    image: francken/v2-nginx
    links:
      - php
    volumes_from:
      - php
    volumes:
      - ./docker/nginx/francken.conf:/etc/nginx/conf.d/francken.conf
    restart: always
    networks:
      - default
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.backend=francken-web"
      - "traefik.frontend.rule=Host:francken.nl.localhost"
      - "traefik.port=80"
      - "traefik.docker.network=traefik_webgateway"

  fly-images:
    image: flyimg/flyimg-build
    restart: always
    networks:
      - default
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.backend=francken-images-web"
      - "traefik.frontend.rule=Host:francken-images.nl.localhost"
      - "traefik.port=80"
      - "traefik.docker.network=traefik_webgateway"

  mailhog:
    image: mailhog/mailhog
    networks:
      - default
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.backend=francken-email-web"
      - "traefik.frontend.rule=Host:francken-mail.nl.localhost"
      - "traefik.port=8025"
      - "traefik.docker.network=traefik_webgateway"

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: francken
      MYSQL_PASSWORD: leden
      MYSQL_DATABASE: francken
    volumes:
      - mysql:/var/lib/mysql

  legacy-db:
    image: francken/mysql
    volumes:
      - ./database/francken-db.sql:/docker-entrypoint-initdb.d/dump.sql
    environment:
      - MYSQL_USER=francken
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=francken
    restart: always

  redis:
    image: redis:4-alpine
    ports:
      - 16379:6379
    volumes:
      - redis:/data

volumes:
  mysql:
    driver: "local"
  redis:
    driver: "local"
