version: '2'

networks:
  traefik:
    external:
      name: traefik_webgateway

services:
  php:
    image: francken/php
    links:
      - mysql
      - legacy-db
      - redis
      - mailhog
    working_dir: /var/www/francken
    volumes:
      - ./:/var/www/francken
    environment:
      - CACHE_DRIVER=redis
      - SESSION_DRIVER=redis
      - QUEUE_DRIVER=redis
      - REDIS_HOST=redis
      - APP_URL=http://francken.nl.localhost
      - MAIL_HOST=mailhog
      - MAIL_PORT=1025
    # volumes_from:
    #   - data

  scheduler:
    image: francken/scheduler
    links:
      - legacy-db
      - redis
    working_dir: /var/www/francken
    volumes:
      - ./:/var/www/francken
    restart: always

  queue-worker:
    image: francken/scheduler
    links:
      - legacy-db
      - redis
    working_dir: /var/www/francken
    volumes:
      - ./:/var/www/francken
    restart: always
    command: php artisan horizon

  # data:
  #   image: busybox
  #   volumes:
  #     - /var/www/francken/storage

  nginx:
    image: francken/nginx
    links:
      - php
    volumes_from:
      - php
    restart: always
    networks:
      - default
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.backend=francken-web"
      - "traefik.frontend.rule=Host:francken.nl.localhost"
      - "traefik.port=80"
      - "traefik.docker.network=traefik_webgateway"

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: francken
      MYSQL_PASSWORD: leden
      MYSQL_DATABASE: francken
    volumes:
      - mysql:/var/lib/mysql

  composer:
    image: composer:1.7
    volumes_from:
      - php
    working_dir: /var/www/francken

  npm:
    image: node:8.2
    volumes_from:
      - php
    working_dir: /var/www/francken

  fly-images:
    image: flyimg/flyimg-build
    restart: always
    networks:
      - default
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.backend=francken-images-web"
      - "traefik.frontend.rule=Host:francken-images.nl.localhost"
      - "traefik.port=80"
      - "traefik.docker.network=traefik_webgateway"

  legacy-db:
    image: francken/mysql
    volumes:
      - ./database/francken-db.sql:/docker-entrypoint-initdb.d/dump.sql
    environment:
      - MYSQL_USER=francken
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=francken
    restart: always

# This service is mostly identical to the php service except that it also
# intalls xdebug so we can check for coverage
  test_coverage:
    image: francken/php:with-xdebug
    volumes_from:
      - php
    links:
      - mysql
    environment:
      DB_CONNECTION: testing

  redis:
    image: redis:4-alpine
    ports:
      - 16379:6379
    volumes:
      - redis:/data

  mailhog:
    image: mailhog/mailhog
    networks:
      - default
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.backend=francken-email-web"
      - "traefik.frontend.rule=Host:francken-mail.nl.localhost"
      - "traefik.port=8025"
      - "traefik.docker.network=traefik_webgateway"

volumes:
  mysql:
    driver: "local"
  redis:
    driver: "local"
