version: '2'

networks:
  traefik:
    external:
      name: traefik_webgateway

services:
  php:
    image: francken/php
    links:
      - mysql
      - legacy-db
    volumes:
      - ./:/var/www/francken
    # volumes_from:
    #   - data

  # data:
  #   image: busybox
  #   volumes:
  #     - /var/www/francken/storage

  nginx:
    image: francken/nginx
    links:
      - php
    volumes_from:
      - php
    restart: always
    networks:
      - default
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.backend=francken-web"
      - "traefik.frontend.rule=Host:francken.nl.localhost"
      - "traefik.port=80"
      - "traefik.docker.network=traefik_webgateway"

  mysql:
    image: francken/mysql
    environment:
      - MYSQL_USER=francken
      - MYSQL_PASSWORD=leden
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=francken
    restart: always

  composer:
    image: composer/composer:alpine
    volumes_from:
      - php
    working_dir: /var/www/francken

  npm:
    image: node:7.4
    volumes_from:
      - php
    working_dir: /var/www/francken

  yarn:
    image: kkarczmarczyk/node-yarn
    volumes_from:
      - php
    working_dir: /var/www/francken
    command: yarn


  fly-images:
    image: flyimg/flyimg-build
    restart: always
    networks:
      - default
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.backend=francken-images-web"
      - "traefik.frontend.rule=Host:francken-images.nl.localhost"
      - "traefik.port=80"
      - "traefik.docker.network=traefik_webgateway"

  legacy-db:
    image: francken/mysql
    volumes:
      - ./database/francken-db.sql:/docker-entrypoint-initdb.d/dump.sql
    environment:
      - MYSQL_USER=francken
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=francken
    restart: always

# This service is mostly identical to the php service except that it also
# intalls xdebug so we can check for coverage
  test_coverage:
    image: francken/php:with-xdebug
    volumes_from:
      - php
    links:
      - mysql
    environment:
      DB_CONNECTION: testing
